### ISSUE TITLE
How exactly could I use Complex numbers?

### ISSUE THREAD

**Issue by MilitaoLucas** [Ivorforce/NumDot#143]
Hello. I was trying to create an ndarray and realized that numdot has complex number support. The problem is that I couldn't find any function that returns an imaginary number (like conj or imag). Is that not added yet? I do realize that maybe the imaginary results where more of a way to deal with the fft calculations.

**Comment by Ivorforce** [comment]
Hi! Imaginary numbers are planned for the next release (and mostly implemented by now), but not available yet in the latest release. I'm planning to get the next version out within the week though :)

**Comment by MilitaoLucas** [comment]
OK, thank you. Sincerely this project seems fantastic. You work pretty fast lol!

**Comment by Ivorforce** [comment]
Thank you! ☺️
The functions I currently have implemented for the upcoming release are listed in the [latest changelog](https://numdot.readthedocs.io/en/latest/setup/changelog.html), by the way.
I don't work with complex numbers in NumPy often - let me know if I'm missing anything you consider important, and I should be able to add it before the next release!

**Comment by MilitaoLucas** [comment]
It seems fine the way it is. I was trying to make a 2d game which flips in a third dimension. I wanted to represent the flipped node (with two children, one for each side) as a ndarray with complex numbers. I didn't want to use quartenions as I only need an extra axis for flipping. I temporarily solved it using the default godot array with a pair of elements for each element. It doesn't work as well because I can't multiply by a complex number to change orientations. I am trying to make symmetry operators that do basically that ($e^{i\theta}$). As I want to create the smallest pattern possible that fills the entire space using those transformations. I thought using complex numbers would create simpler operators. So, I think that if dot and cross products work with complex arrays this is totally fine for my use case!

**Comment by Ivorforce** [comment]
[Release v0.7](https://github.com/Ivorforce/NumDot/releases) is available now, and it includes support for complex numbers (and cross products, which I didn't actually have before).
Let me know if anything isn't working as expected!

**Comment by MilitaoLucas** [comment]
Thank you!
