### ISSUE TITLE
Rounding functions (ceil, floor, rint...)

### ISSUE THREAD

**Issue by Ivorforce** [Ivorforce/NumDot#50]
The relevant [xtensor functions can be found here](https://xtensor.readthedocs.io/en/latest/quickref/math.html#nearest-integer-operations).

**Comment by Krishn1412** [comment]
hey @Ivorforce Can you assign this to me? Also can you specify where do you need these functions defined?

**Comment by Ivorforce** [comment]
Hi @Krishn1412, great to hear you want to contribute! I'll assign the task to you.

You have good timing; I just finished refactoring parts of the codebase. 

I would expect to find all these functions in `vatensor/round.h/cpp` files (analogous to `vatensor/trigonometry.h/cpp`. And of course defined, implemented and bound as static functions to `nd.h` (also analogous to the sin / cos / tan functions).

**Comment by Ivorforce** [comment]
Fixed by #51.
